# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: "%kernel.project_dir%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    _instanceof:
        Psr\Log\LoggerAwareInterface:
            calls:
                - ['setLogger', ['@Monolog\Logger']]
        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]
        Symfony\Component\Serializer\SerializerAwareInterface:
            calls:
                - ['setSerializer', ['@serializer']]
        App\Handler\Request\RequestHandlerInterface:
            tags: ['handler.request']
        App\Handler\Error\ErrorHandlerInterface:
            tags: ['handler.error']

    # RequestHandler
    App\Handler\Request\RequestHandlerInterface: '@App\Handler\Request\ChainRequestHandler'
    App\Handler\Request\ChainRequestHandler:
        arguments:
            $handlers: !tagged_iterator handler.request
        tags:
            - { name: handler.request, priority: 0 }
    App\Handler\Request\SymfonyRequestHandler:
        tags:
            - { name: handler.request, priority: -1 }
    App\Handler\Request\NotFoundRequestHandler:
        tags:
            - { name: handler.request, priority: -99 }

    # ErrorHandler
    App\Handler\Error\ErrorHandlerInterface: '@App\Handler\Error\ChainErrorHandler'
    App\Handler\Error\ChainErrorHandler:
        arguments:
            $handlers: !tagged_iterator handler.error
        tags:
            - { name: handler.error, priority: 0 }
    App\Handler\Error\DefaultErrorHandler:
        tags:
            - { name: handler.error, priority: -1 }

    # logger
    Monolog\Logger:
        factory: ['@App\Logger\ConsoleLoggerFactory', create]
